# Generated by Django 4.1.5 on 2023-02-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_category_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
