# Generated by Django 4.1.5 on 2023-02-03 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_follower_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.follower')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_privacy', to='network.privacy'),
        ),
    ]
