# Generated by Django 4.1.5 on 2023-02-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_follower_group_privacy_post_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Privacy',
        ),
    ]
