# Generated by Django 4.1.5 on 2023-02-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_post_privacy_delete_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='privacy',
            new_name='private',
        ),
    ]
