# Generated by Django 4.1.5 on 2023-02-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_profile_delete_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
