# Generated by Django 4.1.5 on 2023-02-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_post_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(blank=True, default=''),
        ),
    ]
