# Generated by Django 4.1.5 on 2023-02-07 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_post_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Followers_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
