# Generated by Django 4.1.5 on 2023-02-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_alter_profile_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.URLField(default='https://www.publicdomainpictures.net/pictures/130000/nahled/grey-gradient-background-1439642315lMp.jpg'),
        ),
    ]
