# Generated by Django 4.1.5 on 2023-02-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_request_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted')], default=1),
        ),
    ]
