# Generated by Django 4.1.5 on 2023-01-10 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_w_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='w_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
