# Generated by Django 4.1.5 on 2023-01-12 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_date_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='products',
            field=models.ManyToManyField(blank=True, to='auctions.listing'),
        ),
    ]
