# Generated by Django 4.1.5 on 2023-01-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_category_alter_listing_w_bidder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
    ]
